site_name: Basis Wiki

nav:
  - Übersicht: index.md
  
  - Module I Das Konzept und die Theorie:
    - Open Source & Proprietäre Software: content/module1/OpenSource&Linux-Community.md
    - Open-Source-Software und Lizenzierung: content/module1/opensource_lizenzen.md
    - Linux Evolution und beliebte Betriebssysteme: content/module1/linux_evolution.md
    - Das Linux-Betriebssystem: content/module1/das_linux_betriebssystem.md
    - Dateisystem-Hierarchie: content/7.md
    - Netzwerk: content/8.md


  - Module II Die Grundlagen der Command-Line:
    - Grundlagen der Kommandozeile: content/3.md
    - Die Kommandozeile zur Hilfe nutzen: content/4.md    
    - Verzeichnissen und Anzeigen von Dateien: content/4.md    
    - Erstellen, Verschieben und Löschen von Dateien: content/4.md 

  - Module III Automatisierung und Skripting:
    - Verknüpfung von Befehlen: content/3.md
    - Archivierung von Dateien in der Kommandozeile: content/4.md    
    - Suchen und Extrahieren von Daten aus Dateien: content/4.md    
    - Befehle in ein Skript umwandeln: content/4.md 
    - Automatisierung von Aufgaben mit Cron: content/4.md
    - Fortgeschrittenes Skripting: content/4.md
  
  - Module IV Systemadministration und Sicherheit:
    - Benutzer- und Gruppenverwaltung: content/3.md
    - Verwalten von Dateiberechtigungen und Eigentum: content/4.md
    - Systemüberwachung und Protokollierung: content/4.md    
    - Softwareinstallation und -verwaltung: content/4.md    
    - Netzwerksicherheit und Firewall-Konfiguration: content/4.md 
    - Backup-Strategien und Wiederherstellung: content/4.md

  - Module V Zusammenführung und Zielsetzung:
    - Wichtige Open-Source-Anwendungen: content/3.md
    - ICT-Fähigkeiten und Arbeiten in Linux: content/4.md
 


theme:
  name: material
  palette:
    # primary: blue
    # accent: green
    primary: amber
    accent: deep orange
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true

extra_css:
  - stylesheets/logo.css
  - stylesheets/grid.css
  - stylesheets/video_admonition.css
  - stylesheets/python_tutor_admonition.css
  - stylesheets/mermaid.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
    - search
    - macros

extra:
  social:
    - icon: fontawesome/solid/k
      link: https://www.kununu.com/de/qualidy
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/company/qualidy
    - icon: material/google
      link: https://www.google.com/search?sca_esv=7e6ba2047fcb60f3&uds=AMwkrPtyB8MsmozA4Lwzqy2G2HCu-abqzc6moOG48q3gP5dtjTRzC2Ws0eSwcyLXDfZNuYCrZ7ByIreHLG9th3vKLekPoVeey0tumAbet4cVLQRLzdRFhUbOGbnyp3xo1V0hzzaNmkCN&si=AKbGX_rcuucMgom2rba1cdwsvM2SVoIkP2btyqGMV4t0GuHIs4sGV_1tpuqR0YHG4Rzd9SdJcL-lW6E-2aJA5azZLTKkIOrZ2j2aWwoBkVbdEJ0o0GPcQhs%3D&q=Qualidy+GmbH+Rezensionen&sa=X&ved=2ahUKEwibsbnSgcmFAxXNQvEDHaVYCiAQ3PALegQIRxAF
    - icon: fontawesome/solid/globe
      link: https://qualidy.de

watch:
  - tasks

copyright: Copyright &copy; 2026 Qualidy GmbH